CREATE TABLE IF NOT EXISTS spotify_artist (
    href TEXT,
    id TEXT,
    name TEXT,
    popularity BIGINT,
    type TEXT,
    uri TEXT,
    external_urls_spotify TEXT,
    followers_href TEXT,
    followers_total BIGINT,
    images_0_height BIGINT,
    images_0_url TEXT,
    images_0_width BIGINT,
    images_1_height BIGINT,
    images_1_url TEXT,
    images_1_width BIGINT,
    images_2_height BIGINT,
    images_2_url TEXT,
    images_2_width BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
